[package]
name = "markdown-convertor"
version = "0.1.0"
authors = ["Aikepaer Abuduweili <abdvls@gmail.com>"]
edition = "2018"


[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2.63"
regex = "1"
